name: big-data-project
channels:
  - defaults
dependencies:
  - python=3.8.13
  - pip=22.2.2
  - git
  - pip:
    - -e git+https://github.com/LUH-DBS/DataDiscoveryBenchmark.git#egg=datadiscoverybench
    - duckdb==0.5.1
    - fastparquet
    - autogluon==0.6.0
    - tqdm
    - fastparquet
